#
# ── Ramliya NTP/PTP appliance sysctl ──
#
# VM tuning
#
vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
vm.dirty_expire_centisecs = 1000
vm.dirty_writeback_centisecs = 250
vm.min_free_kbytes = 4096
vm.swappiness = 0

# Hardening
#
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 1
fs.protected_regular = 1

# Network tuning
#
net.unix.max_dgram_qlen = 64
#
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1

# Kernel tuning
#
kernel.printk = 4 4 1 4
kernel.dmesg_restrict = 1
kernel.kptr_restrict = 1
#
# kernel.sched_rt_runtime_us = 950000
#
# kernel.panic = 10
# kernel.panic_on_oops = 1

