# ── Ramliya NTP/PTP appliance sysctl ──

vm.swappiness = 0

vm.dirty_ratio = 10
vm.dirty_background_ratio = 5
vm.dirty_expire_centisecs = 1000
vm.dirty_writeback_centisecs = 250

# hardening
fs.protected_hardlinks = 1
fs.protected_symlinks = 1

# kernel.sched_rt_runtime_us = 950000

# autorepair unattended appliance 
# 
#kernel.panic = 10
#kernel.panic_on_oops = 1
